name: Upload Python Package
on:
    release:
        types: [created]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.1
            - name: Setup Python (3.8)
              uses: actions/setup-python@v5
              with:
                python-version: "3.8"
            - name: Upgrade Pip, Build, Twine
              run: |
                python -m pip install --upgrade pip
                python -m pip install --upgrade build
                python -m pip install twine
            - name: Build Source
              run: |
                python -m build
            - name: Publish Source
              env:
                TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
                TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
              run: |
                twine upload dist/*